### ISSUE TITLE
Ideas for Handbook Pages

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/community#105]
What processes do we have in CHAOSS that could each constitute a single page?
Here are four ideas

1) Mentoring (e.g., GSoC, Outreachy, CommunityBridge)
    - Organisation administrators
    - Finding Mentors
    - Selecting Mentees
    - Integrating Mentees
    - Coordinating between Mentors and Mentees
2) Working Group
    - Starting a working group
    - meeting on regular calls
    - using mailing list
    - engaging people asynchronously
3) Releasing metrics
    - Process
    - Infrastructure
4) Website
    - Adding new page
    - updating a page
    - removing a page

**Comment by GeorgLink** [comment]
5. Organizing CHAOSScon

**Comment by BenLloydPearson** [comment]
Will each of the top level items (Mentoring, Working Group, etc.) have their own page? I think 2 would definitely need a top level page, but I'm not sure if the others would have enough content to justify them because most of the content would be in the lower pages.

If it has a top level page, I think 2. Working Group could be condensed into the following pages:
* Start a Working Group
* Working Group Communications and Planning (this would combine the last 3 elements from your list)

**Comment by GeorgLink** [comment]
I think @BenLloydPearson is right. What content goes on which page is malleable and we'll decide as we write those pages.

**Comment by GeorgLink** [comment]
I started a draft for the CHAOSScon organizing page:
https://docs.google.com/document/d/1CCrN1lRkN-pWNrXL4mL0_XSzInX6VZ1X9JZSOQQicHw/edit

**Comment by GeorgLink** [comment]
New Section: CHAOSScast

**Comment by ElizabethN** [comment]
I believe all these topics have been covered in the current version of the [Community Handbook](https://handbook.chaoss.community/community-handbook/), so I'm closing this issue.

**Comment by GeorgLink** [comment]
Yes, especially thanks to @jaskiratsingh2000's amazing work on the Handbook.

**Comment by jaskiratsingh2000** [comment]
Thanks
