### ISSUE TITLE
Reviewing our use DCO for usability, personal safety, validity

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/community#289]
I appreciate that we want a contributor license agreement in our process. It's a valuable part of a growing organization to take it up. I want to go over some reasons I think DCO isn't helping us with that, hopefully concisely:

  - We are having issues with contributors knowing about the DCO, using the DCO, and patching mistakes with DCO. We have some [really](https://github.com/chaoss/wg-dei/pull/347) good [examples](https://github.com/chaoss/wg-dei/pull/343) in DEI. I've also personally had issues when I use the GitHub UI. 
      - I've experienced issues where I have to completely remake a PR because my DCO commit locks up and I don't know enough Git to resolve it. This could be bad for new contributors.
  - Using DCO introduces ethics issues around real names. For the validity of the DCO, you must use your real name. Neither pseudonyms nor anonymization will work. I think this is a really big ask.
      - Some good questions around this topic of DCO & naming are well described in [this issue](https://github.com/go-gitea/gitea/issues/7389).
  - I've seen a few spots where good arguments are made that DCO is not a valid CLA. Here is [one argument](https://writing.kemitchell.com/2021/07/02/DCO-Not-CLA.html) for that case. 
     - The validity becomes a bigger problem if we ask the submitter during the review of their PR.
     - I've also seen maintainers "just set it to pass" for other maintainers, including me, because of the difficulty.

With these arguments in mind, I propose we, as an organization:
 - Remove our integration of the DCO in CHAOSS repositories
 - Search for an alternative that provides an explicit opportunity for agreement

**Comment by GeorgLink** [comment]
Great arguments.

The DCO requirement comes from the Linux Foundation. If we want to change it, we need to involve the Linux Foundation.

**Comment by germonprez** [comment]
HI all. 

After talking with folks at the LF, I really think this is something we need to keep. The primary reasons around around ensuring that contributions are 

The DCO indicates that contributors are responsible for the code that they contribute and that they understand that the contribution is under the terms of the [..] project licenses."

Not having the DCO also contributes to pattern that may result in malicious code being contributed because of anonymity. I think our only other option is a CLA which is much more involved and even higher overhead.
