### ISSUE TITLE
6 months before Event: Optional: Release and advertise CFP

### ISSUE THREAD

**Issue by the-techgurl** [chaoss/community#606]
- Optional: Release and advertise CFP for CHAOSScon NA 2024
- To be overseen by the Content Coordinator - TBD

**Comment by geekygirldawn** [comment]
Since we don't have much time to prep for this and we're just finishing CHAOSScon EU, we decided not to have a CFP, but we do need a content coordinator who will need to build the schedule and make sure that we have activities.

We've talked about having interactive sessions where people can work together on some metrics definitions and insight guides, but this will require some prep from the content coordinator or someone they delegate to.

We also talked about doing lightning talks.

**Comment by geekygirldawn** [comment]
cc: @GeorgLink since we were talking about this a few min ago.

**Comment by geekygirldawn** [comment]
Closing this, since there are 2 other issues about speakers #613 and keynotes #614
